#LOCAL:
server:
  port: 8081
redsky:
  baseUrl: https://redsky-uat.perf.target.com/redsky_aggregations/v1/redsky/case_study_v1?key=
  key: ${redsky_key:3yUxt7WltYG7MFKPp7uyELi1K40ad2ys}

management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles:
              - 0.95
              - 0.99
            percentiles-histogram: true

  endpoint:
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10
        failureRateThreshold: 50
        registerHealthIndicator: true
        ignoreExceptions: com.myretail.api.exception.NotFoundException
        recordExceptions: com.myretail.api.exception.ApplicationException

    instances:
      redsky:
        baseConfig: default
